<?php
/* This file is automatically generated, DO NOT modify */
class EpUserService
{
	public static function QueryAccountById($id) {
		MedooManager::setDbConfig(ConfigManager::$db_config);
		$ret = MedooManager::queryOne('ep_user','tb_account',array('userid'=>$id));
		return $ret;
	}
	public static function QueryAccountByIdList($id) {
		MedooManager::setDbConfig(ConfigManager::$db_config);
		if (!is_array($id)) {
			$id = array($id);
		}
		return MedooManager::query('ep_user','tb_account',array('userid'=>$id));
	}
	public static function QueryAccount($conditions) {
		MedooManager::setDbConfig(ConfigManager::$db_config);
		return MedooManager::query('ep_user','tb_account',$conditions);
	}
	public static function QueryOneAccount($conditions) {
		MedooManager::setDbConfig(ConfigManager::$db_config);
		return MedooManager::queryOne('ep_user','tb_account',$conditions);
	}
	public static function AddAccount($params) {
		MedooManager::setDbConfig(ConfigManager::$db_config);
		return MedooManager::insert('ep_user','tb_account',$params);
	}
	public static function UpdateAccountById($id, $params) {
		MedooManager::setDbConfig(ConfigManager::$db_config);
		if (!is_array($id)) {
			$id = array($id);
		}
		return MedooManager::update('ep_user','tb_account',$params,array('userid'=>$id));
	}
	public static function DeleteAccountById($id) {
		MedooManager::setDbConfig(ConfigManager::$db_config);
		if (!is_array($id)) {
			$id = array($id);
		}
		return MedooManager::delete('ep_user','tb_account',array('userid'=>$id));
	}
	public static function CountAccount($conditions=array()) {
		MedooManager::setDbConfig(ConfigManager::$db_config);
		return MedooManager::count('ep_user','tb_account',$conditions);
	}
	public static function CountAndQueryAccount($conditions=array()) {
		MedooManager::setDbConfig(ConfigManager::$db_config);
		return MedooManager::countAndQuery('ep_user','tb_account',$conditions);
	}
	public static function SumAccount($column, $conditions=array()) {
		MedooManager::setDbConfig(ConfigManager::$db_config);
		return MedooManager::sum('ep_user','tb_account',$column,$conditions);
	}
	public static function AddOrUpdateAccount($params,$conditions) {
		MedooManager::setDbConfig(ConfigManager::$db_config);
		$ret = self::QueryAccount($conditions);
		if(empty($ret)) {
			return self::AddAccount(array_merge($params,$conditions));
		}
		$info = $ret[0];
		$to_update = false;
		foreach($params as $key => $value) {
			if ($info[$key] != $value){
				$to_update = true;
				break;
			}
		}
		if($to_update){
			return self::UpdateAccount($params,$conditions);
		}
		return true;
	}
}